#!/bin/sh

cd "$(dirname "$0")"

REPO=tv.boxeeplay.tv4play2
if [[ `uname -s` == Darwin* ]]
then
    TARGET=$HOME/Library/Application\ Support/BOXEE/UserData/apps
    echo "Copying $REPO to $TARGET"

    rm -rf "$TARGET/$REPO"
    cp -r "$REPO" "$TARGET"
else
    echo "Your platform is currently not supported."
fi
